name: Container
on: push

jobs:
    docker-steps:
        runs-on: ubuntu-lates
        container:
            image: node:18-alpine3.17
        steps:
            - name: Log node version
              run: node -v
            - name: Step with docker
              uses: docker://node:16-alpine3.17
              with:
                  entrypoint: "/bin/echo"
                  args: "Hello World"
            - name: Log node version
              uses: docker://node:16-alpine3.17
              with:
                  entrypoint: /usr/local/bin/node
                  args: -v
            - uses: actions/checkout@v1
            - name: Log node version
              uses: docker://node:16-alpine3.17
              with:
                  entrypoint: ./script.sh
                  args: "Some string"
    node-docker:
        runs-on: ubuntu-latest
        services:
            app:
                image: alialaa17/node-api
                ports:
                    - 3001:3000
            mongo:
                image: mongo
                ports:
                    - "27017:27017"
            image: node:20-alpine3.17
        steps:
            - name: Post a user
              run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "helo","address": "dwde"}'''
            - name: Get users
              run: curl http://localhost:3001/api/user
